### ISSUE TITLE
Group management

### ISSUE THREAD

**Issue by peppinoita** [braydondavis/Nerd-Gaming-Public#3]
Hi Braydon.
Is there a way to manage the groups?
I can't find a way to do it.
If I empty the mysql tables and I restart the resource the database tables are automatically filled with the old data.
Thanks.

**Comment by braydondavis** [comment]
Hello peppinoita,

In the next version of Nerd Gaming (v1.1.4) there will be a new button on the group panel that will allow administrators to manage groups. This feature has already been scripted and commited here on GitHub to the development branch. You can download the following version of the NGGroups resource to have this feature: https://github.com/braydondavis/Nerd-Gaming-Public/tree/development/resources/NGGroups

This groups resource only uses the database when it is first started and when it stops. When the resource is started it will create the tables and query all the existing groups and store them into a table. When the group resource is stopped it deletes all information from all the group tables and puts in new information. I used this technique for better overall performance so that it wouldn't have to query the database anytime it wanted to do something, it just has to update Lua table.

Thank you,
xXMADEXx

**Comment by peppinoita** [comment]
Thanks for your info and thanks for sharing this gamemod
